version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 192.168.59.1:5432:5432
    env_file:
      - ./backend_main_django/project/.env