version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./backend_main_django/project/.env

  web:
    build: backend_main_django
    image: django_app
    volumes:
      - ./backend_main_django:/code
    env_file:
      - ./backend_main_django/project/.env
    depends_on:
      - db

volumes:
  db_data:
