apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "* * * */1 *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: zusmanone/django_test:step6
            imagePullPolicy: IfNotPresent
            command:
            - python
            - manage.py
            - clearsessions
          restartPolicy: OnFailure