apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 30
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: migrate
    spec:
      containers:
      - name: hello-world
        image: zusmanone/django_test:step6
        envFrom:
          - secretRef:
              name: mysecret
        command: ["python", "manage.py","migrate","--noinput"]
      restartPolicy: OnFailure
