apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrate
    spec:
      containers:
      - name: hello-world
        image: zusmanone/django_test:step6
        command: ["python", "manage.py","migrate","--noinput"]
      restartPolicy: OnFailure
